FROM python:3.12-slim

WORKDIR /app

# The whole app is a static site now (see static/app.js) - every
# project's workbook.json and crop PNGs are pre-baked into data/ at
# authoring time (tools/add_chapter.py), not generated by a runtime
# API. Nothing here needs a real application server, just something to
# serve these files over HTTP - python's own http.server does that with
# no extra dependencies to install or keep patched.
COPY index.html ./
COPY static ./static
COPY data ./data

EXPOSE 8000
CMD ["sh", "-c", "python3 -m http.server ${PORT:-8000}"]
